In [9]:
from scipy.signal import convolve2d
import numpy as np
from math import atan, degrees

In [25]:
def s(r,t):
    q = []
    for i in range(r,r+y.shape[0]):
        w = []
        for j in range(t,t+y.shape[0]):
            w.append(x[i][j])
        q.append(w)
        
    q = np.array(q)
    return q

output = np.zeros(x.shape)
start_x = start_y = 1
for i in range(len(x)-len(y)+1):
    for j in range(len(x)-len(y)+1):
        output[start_x,start_y] = (s(start_x-1,start_y-1)*y).sum()
        start_y += 1
    start_x += 1
    start_y = 1

print(output)

[[  0.   0.   0.   0.]
 [  0. 297. 229.   0.]
 [  0. 385.  98.   0.]
 [  0.   0.   0.   0.]]


In [14]:
x = np.array([[120,125,212,239],
               [90,100,180,200],
               [85,195,200,210],
               [75,212,255,195]])
y = np.array([[-1,0,1],
               [-1,0,1],
               [-1,0,1]])
z = np.array([[1,1,1],
               [0,0,0],
               [-1,-1,-1]])
lap_x = np.array([[4,4,12,12,12],
               [4,4,12,12,12],
               [4,4,12,12,12],
               [4,4,8,8,8],
               [4,4,8,8,8]])
lap = np.array([[0,1,0],
                [1,-4,1],
                [0,1,0]])

def slice_array(array, start_x, start_y, filter_shape):
        slice = []
        for itr_i in range(start_x, start_x+filter_shape):
            row = []
            for itr_j in range(start_y, start_y+filter_shape):
                row.append(array[itr_i][itr_j])
            slice.append(row)
            
        return np.array(slice)
    
def convolution(x, y):
    output = np.zeros(x.shape)
    start_x = start_y = 1
    for i in range(x.shape[0]-len(y)+1):
        for j in range(x.shape[1]-len(y)+1):
            output[start_x,start_y] = (slice_array(x, start_x-1, start_y-1, y.shape[0])*y).sum()
            start_y += 1
        start_x += 1
        start_y = 1

    return output

def angle_calc(gradient_magnitude, gradient_x, gradient_y):
    gradient_angle = np.zeros(gradient_magnitude.shape)
    for itr_x in range(gradient_angle.shape[0]):
        for itr_y in range(gradient_angle.shape[1]):
            if gradient_x[itr_x][itr_y] != 0:
                gradient_angle[itr_x][itr_y] = degrees(atan(gradient_y[itr_x][itr_y]/gradient_x[itr_x][itr_y]))
            else:
                gradient_angle[itr_x][itr_y] = 0
    return gradient_angle

f=convolution(x,y)
g=convolution(x,z)
ang = angle_calc(x,f,g)
print(ang)
# print(convolution(lap_x,lap))

[[  0.           0.           0.           0.        ]
 [  0.          -4.42820884  -7.21737916   0.        ]
 [  0.         -24.07285875 -61.69924423   0.        ]
 [  0.           0.           0.           0.        ]]
